language: ruby
rvm: 2.2.0
script: bundle exec rake test
env:
  global:
  - secure: Kv+A6z6BNf5K/xIj1FgY7C7gKK2vfZoYHGYW8q5T25CYsbYctXRGIG+/6jZYL3Y2QX1fWSpfj/L4+F11FLxK9mRp2YyeP+ym1WHoDFtP5HRxpfqyghMOi6P8j8HMxBbT1XtJ/lI+tl8EE8RQIFDpqjqP+rUE2XogMC7UvDP9jtQ=
  - secure: Is+WABqvkdRCdoH3R1Lu16GaozSbnn9SiV+COEZSt3LnRS9PEHYBfRs6at8rxjjnZrAvx6i02zH2tMMlcjDNZwvHjPEyH06qncSNuqEMu7ngLNA+pgyxwq4KX59uVSL6qS6tR7zr3oz0XF6ZTRJAdNUt0EXYuO6aRsDbUQ734jc=
  - secure: Cfkou2vOaUKa7h/K8H/Tekoz8UIpUwwLpJnTUXEtIMoWADQPVJ++zW9xuZsPcA1u9dIqwQQWASNVFw+gv3zx7L3GNwhReMa19glCl9V0Zb3lO6UZeUL90sn0h+v77rH79a95FP/CHCvc5f/ugmlB795cR8UxacST7aDr4cDB6as=
  - secure: FlUW6nKnmN9Ye6gZXI7axRFt6e1vTVOIxwN1pBtGXIa7HOlEdMG3Aey38jYpJ9mvIjKO8zWuY0ltZHR2H9vz/4zQx/vESSkT0gXQ8C4v/YtjS8L3MyWVH5/IJ3bYWht7JKFaAlAHV6ncPeMjnn1M+4LmczdeZ7h0RB3VhCzRwOM=
  - secure: UowMmQO3K/EUq5Sx3F/NpjyYLXf/zgfb2QCrMWzezbIuzfA3Yd6/eP8GjAeD+AjmG7cQd+Qh8g2DTjIshQkHZXieiAKKg2kBycnx4Ti85Ch7MFqaOY2YndlH3ERRiANszYYSDGxqQ2XKGHcLaJy9XGMwRDari/0BvOtPZz9ko8Y=
