default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: present_development
  host: localhost

test:
  <<: *default
  database: present_test
  host: localhost

production:
  <<: *default
  database: present_production
