# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
common: &common
  github_client_id: <%= ENV['PRESENT_GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['PRESENT_GITHUB_CLIENT_SECRET'] %>
  harvest_subdomain: <%= ENV['PRESENT_HARVEST_SUBDOMAIN'] %>
  harvest_username: <%= ENV['PRESENT_HARVEST_USERNAME'] %>
  harvest_password: <%= ENV['PRESENT_HARVEST_PASSWORD'] %>
  admin_github_ids: <%= ENV['PRESENT_ADMIN_GITHUB_IDS'].split(",") %>
  weekly_rate: <%= ENV['PRESENT_WEEKLY_RATE'] %>
  hourly_rate: <%= ENV['PRESENT_HOURLY_RATE'] %>

development:
  <<: *common
  secret_key_base: 0a52ab402510194db1bca7890437c18352894a392045b4e8698f1ab83196d502e08dd6d5b034bfdf8dc932c422c956376326b5208c5054a0367133555065329c

test:
  <<: *common
  secret_key_base: 2fa5316fc70dd4d0929ee8f7e69e24f8d820cb00aeff0edecf3696bc31df878b3d3eaf9c4d8b660672ccadaf2658ab56950d850f25160bf51b4bb2ede54f8dc3
  github_client_id: <%= ENV['PRESENT_TEST_GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['PRESENT_TEST_GITHUB_CLIENT_SECRET'] %>
  harvest_subdomain: <%= ENV['PRESENT_TEST_HARVEST_SUBDOMAIN'] %>
  harvest_username: <%= ENV['PRESENT_TEST_HARVEST_USERNAME'] %>
  harvest_password: <%= ENV['PRESENT_TEST_HARVEST_PASSWORD'] %>
  admin_github_ids: <%= ENV['PRESENT_TEST_GITHUB_ID'].split(",") %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["PRESENT_SECRET_KEY_BASE"] %>
  raygun_api_key: <%= ENV["RAYGUN_APIKEY"] %>
